name: Cakeclub Bot

on:
  schedule:
    - cron: '0 10 * * 3'   # Wednesday 11:00 Espa√±a (10:00 UTC)
  workflow_dispatch:

jobs:
  cakeclub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Cakeclub Bot
        env:
          EMAIL: ${{ secrets.EMAIL_USER }}
          PASSWORD: ${{ secrets.EMAIL_PASS }}
        run: python cakeclub.py
